# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/martini/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),martini)

$(call add-radio-file-sha1-checked,radio/abl.img,05abb5fef0d0b982eb9c292cdef8f1800d3bd00e)
$(call add-radio-file-sha1-checked,radio/aop.img,ad2cf504a6c14e6a4c5f54b2dc810517b1106f1f)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,cc4f5e52298b6e1a0c0e165ef10327962ef2627b)
$(call add-radio-file-sha1-checked,radio/cpucp.img,f518672ea3398cfb734750e05ff4ced075a17be0)
$(call add-radio-file-sha1-checked,radio/devcfg.img,588dfcc239a63055e11d5baf8ad11d267fb325a4)
$(call add-radio-file-sha1-checked,radio/dsp.img,cff87289aca6247e74f10cd8856001aea70b784c)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,4fefcd7f52d38fa436510cd519f06a55b1a0d5c8)
$(call add-radio-file-sha1-checked,radio/hyp.img,3d60fda5feda8936b4687bcf498ead92acef5acb)
$(call add-radio-file-sha1-checked,radio/imagefv.img,f58beeef2d8f2d3084b5b9af6d058082d4045992)
$(call add-radio-file-sha1-checked,radio/keymaster.img,ab36b45c74dc8625fe93c832d2d9331a3448b332)
$(call add-radio-file-sha1-checked,radio/modem.img,a4a47ab04539494cfcc1d85118d464c018c5ba0a)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,9ce00401d797c677b83712788562f076fbec5c6b)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,bcd981d0d975e649c1b4d2a741ee0bce1ca905bb)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,4b7188e5c3daf71d1c641407fdf89a7170b9b8bc)
$(call add-radio-file-sha1-checked,radio/qupfw.img,e9eb09c2dffe149db377777768aa72623460e965)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,b895356a0ba267d4c514eb414d85d8a33ac11911)
$(call add-radio-file-sha1-checked,radio/splash.img,cef1d4886175660f305e78ab39b7782f8625e431)
$(call add-radio-file-sha1-checked,radio/tz.img,34981d6790cfe740ec1094c37192dfa415770f82)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,66ce413eaac66292b098205f3e19995bbc48a7a7)
$(call add-radio-file-sha1-checked,radio/xbl.img,84b3497b87235ff283c03688ae4eafea42af8541)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,276f144ce4db32cfa6e09fa7d5733258a7dc12ab)

endif
